version: "3"
services:
  strapi:
    image: strapi/strapi:3.6.5
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi

    links:
      - postgres:postgres
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"

  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./dumps:/dumps
    ports:
      - "5432:5432"
