version: '3'
services:
  strapi:
    image: strapi/strapi:3.4.1
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      NODE_ENV: development
      VIRTUAL_HOST: api.setsailrealty.ca
      VIRTUAL_PORT: 1337
      LETSENCRYPT_HOST: api.setsailrealty.ca
    links:
      - postgres:postgres
    volumes:
      - ./app:/srv/app
    expose:
      - 1337
    restart: always 

  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

  nginx-proxy:
    container_name: nginx-proxy
    build: docker/nginx
    restart: always
    ports:
      - 443:443
      - 80:80
      - 1337:1337
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - strapi
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - DEFAULT_EMAIL=abdullah@setsail.ca
      #- ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx-proxy

volumes:
  certs:
  html:
  vhost:
